### ISSUE TITLE
While Running ' ' ' roslaunch mybot_navigation localization.launch ' ' ' 

### ISSUE THREAD

**Issue by Blebot0** [aditirao7/gazebo#1]
ERROR: cannot launch node of type [map_server/map_server]: map_server
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
process[joint_state_publisher-2]: started with pid [24992]
process[robot_state_publisher-3]: started with pid [24993]
process[map_odom_broadcaster-4]: started with pid [24994]
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
ERROR: cannot launch node of type [robot_localization/navsat_transform_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
ERROR: cannot launch node of type [move_base/move_base]: move_base
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share

**Comment by Blebot0** [comment]
Complete OUTPUT:
blebot@blebot:~/nav_ws$ roslaunch mybot_navigation localization.launch
... logging to /home/blebot/.ros/log/ac653234-b455-11ea-94f6-dcf505d27301/roslaunch-blebot-24973.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: ignoring defunct <master /> tag
xacro.py is deprecated; please use xacro instead
started roslaunch server http://blebot:38031/

SUMMARY
========

CLEAR PARAMETERS
 * /ekf_se_map/
 * /ekf_se_odom/
 * /navsat_transform/

PARAMETERS
 * /ekf_se_map/base_link_frame: chassis
 * /ekf_se_map/debug: False
 * /ekf_se_map/frequency: 30
 * /ekf_se_map/imu0: imu_data
 * /ekf_se_map/imu0_config: [False, False, Fa...
 * /ekf_se_map/imu0_differential: False
 * /ekf_se_map/imu0_nodelay: True
 * /ekf_se_map/imu0_queue_size: 10
 * /ekf_se_map/imu0_relative: False
 * /ekf_se_map/imu0_remove_gravitational_acceleration: True
 * /ekf_se_map/initial_estimate_covariance: [1.0, 0, 0, 0, 0,...
 * /ekf_se_map/map_frame: map
 * /ekf_se_map/odom0: odom
 * /ekf_se_map/odom0_config: [False, False, Fa...
 * /ekf_se_map/odom0_differential: False
 * /ekf_se_map/odom0_nodelay: True
 * /ekf_se_map/odom0_queue_size: 10
 * /ekf_se_map/odom0_relative: False
 * /ekf_se_map/odom1: odometry/gps
 * /ekf_se_map/odom1_config: [True, True, Fals...
 * /ekf_se_map/odom1_differential: False
 * /ekf_se_map/odom1_nodelay: True
 * /ekf_se_map/odom1_queue_size: 10
 * /ekf_se_map/odom1_relative: False
 * /ekf_se_map/odom_frame: odom
 * /ekf_se_map/print_diagnostics: True
 * /ekf_se_map/process_noise_covariance: [1.0, 0, 0, 0, 0,...
 * /ekf_se_map/sensor_timeout: 0.1
 * /ekf_se_map/transform_time_offset: 0.0
 * /ekf_se_map/transform_timeout: 0.0
 * /ekf_se_map/two_d_mode: False
 * /ekf_se_map/use_control: False
 * /ekf_se_map/world_frame: map
 * /ekf_se_odom/base_link_frame: chassis
 * /ekf_se_odom/debug: False
 * /ekf_se_odom/frequency: 30
 * /ekf_se_odom/imu0: imu_data
 * /ekf_se_odom/imu0_config: [False, False, Fa...
 * /ekf_se_odom/imu0_differential: False
 * /ekf_se_odom/imu0_nodelay: False
 * /ekf_se_odom/imu0_queue_size: 10
 * /ekf_se_odom/imu0_relative: False
 * /ekf_se_odom/imu0_remove_gravitational_acceleration: True
 * /ekf_se_odom/initial_estimate_covariance: ['1e-9', 0, 0, 0,...
 * /ekf_se_odom/map_frame: map
 * /ekf_se_odom/odom0: odom
 * /ekf_se_odom/odom0_config: [False, False, Fa...
 * /ekf_se_odom/odom0_differential: False
 * /ekf_se_odom/odom0_nodelay: True
 * /ekf_se_odom/odom0_queue_size: 10
 * /ekf_se_odom/odom0_relative: False
 * /ekf_se_odom/odom_frame: odom
 * /ekf_se_odom/print_diagnostics: True
 * /ekf_se_odom/process_noise_covariance: ['1e-3', 0, 0, 0,...
 * /ekf_se_odom/sensor_timeout: 0.1
 * /ekf_se_odom/transform_time_offset: 0.0
 * /ekf_se_odom/transform_timeout: 0.0
 * /ekf_se_odom/two_d_mode: False
 * /ekf_se_odom/use_control: False
 * /ekf_se_odom/world_frame: odom
 * /joint_state_publisher/use_gui: False
 * /move_base/TrajectoryPlannerROS/acc_lim_theta: 1.5
 * /move_base/TrajectoryPlannerROS/acc_lim_x: 0.5
 * /move_base/TrajectoryPlannerROS/acc_lim_y: 0.5
 * /move_base/TrajectoryPlannerROS/holonomic_robot: False
 * /move_base/TrajectoryPlannerROS/max_vel_theta: 1.5
 * /move_base/TrajectoryPlannerROS/max_vel_x: 0.5
 * /move_base/TrajectoryPlannerROS/min_in_place_vel_theta: 0.01
 * /move_base/TrajectoryPlannerROS/min_vel_x: 0.01
 * /move_base/global_costmap/global_frame: odom
 * /move_base/global_costmap/height: 10.0
 * /move_base/global_costmap/inflation_radius: 0.5
 * /move_base/global_costmap/laser_scan_sensor/clearing: True
 * /move_base/global_costmap/laser_scan_sensor/data_type: LaserScan
 * /move_base/global_costmap/laser_scan_sensor/marking: True
 * /move_base/global_costmap/laser_scan_sensor/sensor_frame: hokuyo
 * /move_base/global_costmap/laser_scan_sensor/topic: /mybot/laser/scan
 * /move_base/global_costmap/observation_sources: laser_scan_sensor
 * /move_base/global_costmap/obstacle_range: 2.5
 * /move_base/global_costmap/publish_frequency: 1.0
 * /move_base/global_costmap/raytrace_range: 3.0
 * /move_base/global_costmap/resolution: 0.05
 * /move_base/global_costmap/robot_base_frame: chassis
 * /move_base/global_costmap/robot_radius: 0.5
 * /move_base/global_costmap/static_map: True
 * /move_base/global_costmap/update_frequency: 1.0
 * /move_base/global_costmap/width: 10.0
 * /move_base/local_costmap/global_frame: odom
 * /move_base/local_costmap/height: 6.0
 * /move_base/local_costmap/inflation_radius: 0.5
 * /move_base/local_costmap/laser_scan_sensor/clearing: True
 * /move_base/local_costmap/laser_scan_sensor/data_type: LaserScan
 * /move_base/local_costmap/laser_scan_sensor/marking: True
 * /move_base/local_costmap/laser_scan_sensor/sensor_frame: hokuyo
 * /move_base/local_costmap/laser_scan_sensor/topic: /mybot/laser/scan
 * /move_base/local_costmap/observation_sources: laser_scan_sensor
 * /move_base/local_costmap/obstacle_range: 2.5
 * /move_base/local_costmap/publish_frequency: 1.0
 * /move_base/local_costmap/raytrace_range: 3.0
 * /move_base/local_costmap/resolution: 0.05
 * /move_base/local_costmap/robot_base_frame: chassis
 * /move_base/local_costmap/robot_radius: 0.5
 * /move_base/local_costmap/rolling_window: True
 * /move_base/local_costmap/static_map: False
 * /move_base/local_costmap/update_frequency: 2.0
 * /move_base/local_costmap/width: 6.0
 * /move_base/move_base/DWAPlannerROS/acc_lim_theta: 10.0
 * /move_base/move_base/DWAPlannerROS/max_rot_vel: 1.0
 * /move_base/move_base/DWAPlannerROS/xy_goal_tolerance: 1.0
 * /move_base/move_base/DWAPlannerROS/yaw_goal_tolerance: 1.0
 * /navsat_transform/broadcast_utm_transform: True
 * /navsat_transform/delay: 3.0
 * /navsat_transform/frequency: 30
 * /navsat_transform/magnetic_declination_radians: 0.0429351
 * /navsat_transform/publish_filtered_gps: True
 * /navsat_transform/use_odometry_yaw: False
 * /navsat_transform/wait_for_datum: False
 * /navsat_transform/yaw_offset: 1.570796327
 * /navsat_transform/zero_altitude: False
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.6

NODES
  /
    ekf_se_map (robot_localization/ekf_localization_node)
    ekf_se_odom (robot_localization/ekf_localization_node)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    map_odom_broadcaster (tf/static_transform_publisher)
    map_server (map_server/map_server)
    move_base (move_base/move_base)
    navsat_transform (robot_localization/navsat_transform_node)
    robot_state_publisher (robot_state_publisher/state_publisher)

ROS_MASTER_URI=http://localhost:11311

ERROR: cannot launch node of type [map_server/map_server]: map_server
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
process[joint_state_publisher-2]: started with pid [24992]
process[robot_state_publisher-3]: started with pid [24993]
process[map_odom_broadcaster-4]: started with pid [24994]
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
ERROR: cannot launch node of type [robot_localization/ekf_localization_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
ERROR: cannot launch node of type [robot_localization/navsat_transform_node]: robot_localization
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
ERROR: cannot launch node of type [move_base/move_base]: move_base
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/blebot/nav_ws/src
ROS path [2]=/home/blebot/ar_tag/src
ROS path [3]=/home/blebot/catkin_ws/src
ROS path [4]=/opt/ros/melodic/share
[ WARN] [1592809310.250208512]: The 'state_publisher' executable is deprecated. Please use 'robot_state_publisher' instead
[ WARN] [1592809310.256918445]: The root link chassis has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.

**Comment by aditirao7** [comment]
Updated the ReadMe

**Comment by aditirao7** [comment]
Install the navigation and localization packages for ros. Updated the ReadME.
